name: Build Desktop app

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

env:
  BUILD_TARGET: 'desktop'

jobs:
  build:
    name: Build Desktop app
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List all files
        run: find .
      - name: Run Gradle build
        run: |
          chmod +x gradlew
          ./gradlew build allTests createDistributable
      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v18.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: make
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
      - name: List all files
        run: find .
      - name: List generated files
        run: find ${{ steps.conveyor.outputs.output_path }}
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          # Upload all generated files from the output directory
          files: ${{ steps.conveyor.outputs.output_path }}/*
